# Generated by Django 4.0.3 on 2022-03-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=150)),
                ('date_created', models.DateField()),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
